export default {
	shopifyTraits: [
		{
			type: "shopify_discount",
			label: "Discount Code",
			name: "shopify_discount",
			placeholder: "eg. Lorem Ipsum",
		},
		{
			type: 'refresh',
			label: "",
			name: ' '
		},
		{
			type: 'label',
			label: "",
			name: ' ',
			text: 'OR'
		},
		{
			type: "create_discount_link",
			label: " ",
			name: "info",
		}],
	woocommerTraits: [
		{
			type: "woocommerceCoupon",
			label: "Coupon",
			name: "woocommerceCoupon",
			changeProp: 1,
			placeholder: "Enter coupon code",
		},
		{
			type: "info",
			label: " ",
			name: "info",
			html: `<span class="text-muted">Create a coupon code in WooCommerce -> Coupons and enter that code in this field.</span>`
		},
	],
	nocTraits: [
		{
			
			type: "info",
			label: false,
			name: "info",
			html: `<span class="text-muted">Coupon code for next order is auto-generated by Retainful.No changes required.</span>`
		},
	]
}