export const GET_CONTACT = 'GET_CONTACT'
export const ERROR_CONTACT = 'ERROR_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const ADD_CONTACT = 'ADD_CONTACT'
export const SELECT_ALL_CONTACT = 'SELECT_ALL_CONTACT'
export const DESELECT_ALL_CONTACT = 'DESELECT_ALL_CONTACT'
export const SELECT_CONTACT = 'SELECT_CONTACT'
export const DESELECT_CONTACT = 'DESELECT_CONTACT'
export const UPDATE_CONTACT = 'UPDATE_CONTACT'
export const GET_BY_ID_CONTACT = 'GET_BY_ID_CONTACT'
export const CONTACT_BULK_DELETE = 'CONTACT_BULK_DELETE'
export const FILTER_CONTACT = 'FILTER_CONTACT'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const SUCCESS_FALSE = 'SUCCESS_FALSE'
export const ASSIGN_TAG_SUCCESS = 'ASSIGN_TAG_SUCCESS'
export const CONTACT_LOADING = 'CONTACT_LOADING'
export const CONTACT_ACTION_LOADING = 'CONTACT_ACTION_LOADING'






