export const GET_CAMPAIGN = 'GET_CAMPAIGN'
export const ERROR_CAMPAIGN = 'ERROR_CAMPAIGN'
export const ADD_CAMPAIGN = 'ADD_CAMPAIGN'
export const UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN'
export const CREATE_EMAIL_CAMPAIGN = 'CREATE_EMAIL_CAMPAIGN'
export const SET_CAMPAIGN_LOADING = 'SET_CAMPAIGN_LOADING'
export const SET_SUCCESS_CAMPAIGN = 'SET_SUCCESS_CAMPAIGN'
export const GET_BY_ID_CAMPAIGN = 'GET_BY_ID_CAMPAIGN'

export const SELECT_ALL_TAG = 'SELECT_ALL_TAG'
export const DESELECT_ALL_TAG = 'DESELECT_ALL_TAG'
export const SELECT_TAG = 'SELECT_TAG'
export const DESELECT_TAG = 'DESELECT_TAG'
export const CLEAR_CURRENT_CAMPAIGN = 'CLEAR_CURRENT_CAMPAIGN'
export const SAVE_QUIT_ROUTE = 'SAVE_QUIT_ROUTE'



