export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_ROUTE_ARRAY = 'FETCH_ROUTE_ARRAY'
export const TOGGLE_SHOW = 'TOGGLE_SHOW'
export const TENANT_LOGIN_SUCCESS = 'TENANT_LOGIN_SUCCESS'
export const TENANT_SET_AUTH_LOADING = 'TENANT_SET_AUTH_LOADING'
export const TENANT_LOGIN_FAIL = 'TENANT_LOGIN_FAIL'
export const TENANT_REGISTER_SUCCESS = 'TENANT_REGISTER_SUCCESS'
export const TENANT_USER_LOADED = 'TENANT_USER_LOADED'
export const TENANT_AUTH_ERROR = 'TENANT_AUTH_ERROR'
export const TENANT_REGISTER_FAIL = 'TENANT_REGISTER_FAIL'
export const TENANT_LOGOUT = 'TENANT_LOGOUT'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const SET_ERROR = 'SET_ERROR'
export const USER_LOADING = 'USER_LOADING'






